sources:
-   name: Iran
    url: https://iptvcat.com/iran
-   name: Canada
    url: https://iptvcat.com/canada
-   name: United States of America
    url: https://iptvcat.com/united_states_of_america
-   name: Pakistan
    url: https://iptvcat.com/pakistan
-   name: Undefined
    url: https://iptvcat.com/undefined
-   name: united_kingdom
    url: https://iptvcat.com/united_kingdom
